### ISSUE TITLE
ogr2ogr two geometries

### ISSUE THREAD

**Issue by lacardonap** [dwtkns/gdal-cheat-sheet#15]
Hi @dwtkns 

I have a table with two geometries when I try to do the conversion to geopackage format I only get one. Do you know how can indicate to ogr2ogr which is the field that have the geometry of interest. 

Thank you so much for your help.

Cheers Leo

**Comment by dwtkns** [comment]
Sorry, I don't know off the top of my head and have never really worked with the geopackage format. The [ogr2ogr documentation](http://www.gdal.org/ogr2ogr.html) is pretty extensive, though, so I'd try searching through that if you haven't tried it already.

Good luck!

**Comment by lacardonap** [comment]
Thanks @dwtkns ,

I'll check, if I find anything I'll contribute.

Cheers,
  Leo

**Comment by johnjohndoe** [comment]
@lacardonap Maybe [OGR Virtual Format](http://www.gdal.org/drv_vrt.html) (*.vrt) is helpful.
